learnDJ/base/urls.py
from django.urls import path
from . import views


app_name = 'base'

urlpatterns = [
    path("",views.Home, name="home"),
    path("<int:list_id>/",views.Index, name="index"),
    path("status/<int:list_id>/",views.Status, name="status"),
]

learnDJ/learnDJ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
]

learnDJ/base/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=200)
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class TodoList(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

class Item(models.Model):
    todolist = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

learnDJ/base/views.py
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse, Http404
from .models import Author, TodoList, Item

# Create your views here.

def Index(request, list_id):
    # try:
    #     tdls = TodoList.objects.get(id=item_id)
    # except TodoList.DoesNotExist:
    #     raise Http404("No such item")
    tdl = get_object_or_404(TodoList, pk=list_id)
    return render(request, 'base/item_list.html',{"tdl": tdl})

def Home(request):
    tl = TodoList.objects.all()
    return render(request, 'base/home.html',{"lnk": tl})

def simp(request):
    return render(request, 'base/index.html')


def Status(request, list_id):
    tdl = get_object_or_404(TodoList, pk=list_id)
    try:
        selected_item = tdl.item_set.get(pk=request.POST['item'])
    except (KeyError, Item.DoesNotExist):
        return render(request, 'base/item_list.html',{"tdl": tdl, "error_message": "You did not select a task to complete"})
    else:
        selected_item.completed = True
        selected_item.save()
        return render(request, 'base/item_list.html',{"tdl": tdl})

learnDJ/base/templates/base/base.html
<!DOCTYPE html>


{% load static %}

<html>
    <head>
        <title>{% block title %} DJ learning {% endblock %}</title>
        <meta name="description" content="website description" />
        <meta name="keywords" content="task managers, website keywords" />
        <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
        <link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}" />
        <style>
            table, th, td {
              border: 1px solid blueviolet;
            }
            td {
              border: 1px solid red;
            }
            </style>
    </head>
    <body>
      <div id="main">
        <div id="header">
          <div id="logo">
            <div id="logo_text">
              <!-- class="logo_colour", allows you to change the colour of the text -->
              <h1><a href="{% url 'base:sim' %}">Ropetech<span class="logo_colour">Tasks Board</span></a></h1>
              <h2>Simple. Contemporary. Task Manager.</h2>
            </div>
            <div id="contact_details">
              <p>tel: 254710 509 204</p>
            </div>
          </div>
          <div id="menubar">
            <ul id="menu">
              <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
              <li class="selected"><a href="{% url 'base:home' %}">Home</a></li>
              <li><a href="{% url 'base:home' %}">All Tasks</a></li>
              <li><a href="{% url 'base:home' %}">Comments & Reviews</a></li>
              <li><a href="{% url 'base:home' %}">Accounts</a></li>
              <li><form method="post" action="#" id="search_form">
                {% csrf_token %}
                <p>
                  <input class="search" type="text" name="search_field" placeholder="Search Site....." />
                  <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="{% static 'base/search.png' %}" alt="Search" title="Search" />
                </p>
              </form></li>
            </ul>
          </div>
        </div>
        <div id="site_content">
        {%  block content %}
        {% endblock %}
        </div>
        <div id="footer">
          Copyright &copy; Ropetech | <a href="#">Tasks</a> | <a href="#">Accounts</a> | <a href="#">Authors</a>
        </div>
      </div>
    </body>
</html> 

learnDJ/base/templates/base/home.html
{% extends 'base/base.html' %}

{% block title %} Home {% endblock %}

{%  block content %}
<H1>Home Page</H1>
<br>
    <table>
        <th>TODO LISTS</th>
    {% for l in lnk %}
    <tr>
        <td><a href="{% url 'base:index' l.pk %}">{{ l.title }}</a></td>
    </tr>
    {% endfor %}
    </table>
</div>
{% endblock %}

learnDJ/base/templates/base/item_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Todo Lists {% endblock %}

{%  block content %}
        <div>
            <a type="button" href="{% url 'base:home' %}">BACK</a>
            <p>{{ tdl }}</p>
            {% if error_message %}
            <div style="background-color: rgb(236, 121, 80);"><strong>{{ error_message }}</strong></div>
            {% endif %}
            <form method="post" action="{% url 'base:status' tdl.id %}">
                {% csrf_token %}
                <table>
                    <th>NAME</th><th>Description</th><th>Date</th><th>Completed</th>
                {% for l in tdl.item_set.all %}
                <tr>
                    <td>{{ l.name }}</td>
                    <td>{{ l.description }}</td>
                    <td>{{ l.date }}</td>
                    <td>
                        {% if l.completed %}
                        <!-- <span style="color: greenyellow;"><i>Done</i></span> -->
                        <img type="image" style="border: 0; margin: 2px 2px 2px 2px;" src="{% static 'base/star.png' %}" />
                        {% endif %}
                        <input type="checkbox" id="item{{ forloop.counter }}" name="item" value="{{ l.id }}">
                        <label for="item{{ forloop.counter }}"> Satus</label>
                    
                    </td>
                </tr>
                {% endfor %}
                </table>
                <input type="submit" value="Complete"/>
            </form>
            
        </div>
        
        <!-- <p>{{ iname }}</p> -->
{% endblock %}